name = "blog_pipeline"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Define env vars here if needed, or in the dashboard
NEXT_PUBLIC_SUPABASE_URL=https://fjjptyonjjaotyebhmej.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqanB0eW9uamphb3R5ZWJobWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NzA2MjksImV4cCI6MjA4NTE0NjYyOX0.AAXqlbtUhS-90odIVeO9XjGiPqadLR7-UCuX_qW96mo
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqanB0eW9uamphb3R5ZWJobWVqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTU3MDYyOSwiZXhwIjoyMDg1MTQ2NjI5fQ.6scR0GVcuUPQb5Yx8yxbonGmwdBoPvbzrf1UoYBZU3Q
NODE_VERSION = "24.13.0"